### ISSUE TITLE
Toolbar characters are in chinese

### ISSUE THREAD

**Issue by joaoamorim99** [cipchk/ngx-simplemde#27]
I don't know how to change the characters that appears when i have my mouse up on an icon on the toolbar. Right now they appear in chinese i would like to change to english.

**Comment by cipchk** [comment]
Pls refer to [4. Add simplemde style](https://github.com/cipchk/ngx-simplemde#installation-instructions).

**Comment by paulparton** [comment]
@cipchk the doc you link to appear to be for the summary text below the control. The question is about tooltips on the toolbar, which appear to be hardcoded ("title")

![image](https://user-images.githubusercontent.com/5544897/189563944-2cd0e567-9f69-4e3e-8890-61579ed78716.png)

**Comment by cipchk** [comment]
I can't, trying using `toolbar` property.

> I recommend using [Vditor](https://github.com/Vanessa219/vditor) instead of `simplemde`, About angular version for [@ng-util/markdown](https://github.com/ng-util/ng-util/blob/master/packages/markdown/README.md)
