### ISSUE TITLE
install without angularcli

### ISSUE THREAD

**Issue by Crocsx** [cipchk/ngx-simplemde#4]
I am not using angular cli in the app so I do not have angular.json

I added the css style and js to my page in the index 

`        <link rel="stylesheet" href="node_modules/ngx-simplemde/src/index.css">`
`      <script src="node_modules/simplemde-antd/dist/simplemde.min.js"></script>`

But I do get this error
```

<div class="markdown-editor-container">
    <simplemde [(ngModel)]="text"></simplemde>
</div>

```

`ERROR TypeError: Cannot read property 'style' of undefined`

```
function SimplemdeComponent(cog, cd, zone) {
        this.cog = cog;
        this.cd = cd;
        this.zone = zone;
        this.style = cog.style; <=====
        this.delay = cog.delay || 0;
    }
```

Is it possible to change the way you depend on angularcli, for a more flexible installation ?

**Comment by arifullahjan** [comment]
```
export declare class SimplemdeConfig {
    /**
     * 风格，默认：`antd`
     */
    style?: 'default' | 'antd';
    /**
     * 延迟初始化
     */
    delay?: number;
    /** 全局 `options` */
    options?: {
        [key: string]: any;
    };
}

```


check this out

**Comment by cipchk** [comment]
duplcated of #9
