### ISSUE TITLE
The stackblitz sample shows chinese/japanese characters at the bottom

### ISSUE THREAD

**Issue by HWHofstee** [cipchk/ngx-simplemde#5]
When I run the sample at:

https://stackblitz.com/edit/ngx-simplemde

It shows chinese or japanese characters where I would expect linenumber.

How can I change that?

**Comment by sweatC** [comment]
@HWHofstee Hi!
You just need to include js and css from https://github.com/sparksuite/simplemde-markdown-editor and you will get English for icons and footer:
```json
"styles": [
  "./node_modules/simplemde/dist/simplemde.min.css",
  "src/styles.css"
],
"scripts": [
  "./node_modules/simplemde/dist/simplemde.min.js"
]
```
If you want to just replace status bar line number you can fix it from this package CSS here: https://github.com/cipchk/ngx-simplemde/blob/master/lib/styles/_var.less

**Comment by cipchk** [comment]
@HWHofstee 

Please upgrade to the latest version and modify the parameter `@simplemde-statusbar-lines`.
