### ISSUE TITLE
Typescript errors

### ISSUE THREAD

**Issue by HWHofstee** [cipchk/ngx-simplemde#7]
Upgrading the stackblitz demo to version 1.1.1 results in typescript errors in this part of code:
In app.module.ts:

@NgModule({
  imports:      [ BrowserModule, FormsModule, SimplemdeModule.forRoot({autosave: { enabled: true, uniqueId: 'MyUniqueID' }}) ],
  declarations: [ AppComponent ],
  bootstrap:    [ AppComponent ]
})

Argument of type '{ autosave: { enabled: boolean; uniqueId: string; }; }' is not assignable to parameter of type 'SimplemdeConfig'.
  Object literal may only specify known properties, and 'autosave' does not exist in type 'SimplemdeConfig'.
(property) enabled: boolean

The stackblitz code can be found here:
https://ngx-simplemde-ryzkrt.stackblitz.io

**Comment by ChumaA** [comment]
Try this:
```
  imports: [
    BrowserModule,
    SimplemdeModule.forRoot({
      options: { autosave: { enabled: true, uniqueId: 'MyUniqueID' } }
    })
  ],
```

**Comment by cipchk** [comment]
I think it's resolved
